name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    env:
      FLUIDCOINS_SECRET_KEY: ${{ secrets.FLUIDCOINS_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run test
